name: CI/CD

# Determines when the workflow will run
on:
  # Triggers the workflow on push to main branch
  push:
    branches: [ "main" ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "update"
  update:
    # runs-on: windows-latest  #Github hosted runners
    runs-on: ubuntu-latest  #Github hosted runners
    steps:

    - name: Checkout repo content 
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build
      run: ./gradlew build

    - name: Query
      run: ./gradlew startFuseki query stopFuseki -x reason

    - name: Run Notebook
      run: jupyter nbconvert --to html Report.ipynb
